### ISSUE TITLE
Webpack warning: "This seems to be a pre-built javascript file..."

### ISSUE THREAD

**Issue by azazdeaz** [justinwoo/elm-simple-loader#1]
Hi, thanks a LOT for this loader! It makes using Elm much more fun!

It works perfectly but webpack throws me a warning for the Main.elm file:

WARNING in ./src/Main.elm
Critical dependencies:
12279:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./src/Main.elm 12279:113-120

Do you have any idea how can i get rid of it?

**Comment by justinwoo** [comment]
Used to be because of some big bundle they had in elm-make, but I'm using a newer Elm release that Evan put together for Yosemite, and it went away... Could you paste your output of elm-make?

In my project using this loader, I get this:

```
torscraper/ on master > elm-make --version
elm-make 0.2 (Elm Platform 0.15.1)

Usage: elm-make [FILES...] [--output FILE] [--yes] [--report FORMAT] [--warn]
                [--docs FILE]
  build Elm projects

Available options:
  -h,--help                Show this help text
  --output FILE            Write output to FILE.
  --yes                    Reply 'yes' to all automated prompts.
  --report FORMAT          Format of error and warning reports (e.g.
                           --report=json)
  --warn                   Report warnings to improve code quality.
  --docs FILE              Write documentation to FILE as JSON.

To learn more about a particular command run:
    elm-make COMMAND --help
torscraper/ on master > webpack
Hash: 101a62cfc02f87310a1d
Version: webpack 1.12.2
Time: 2237ms
   Asset     Size  Chunks             Chunk Names
index.js  2.28 MB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 217 hidden modules
```

I tried asking, but I never got an answer for how to suppress the warning, but yeah, I'd hate to say upgrading is the answer, but it might be?

edit: dang! I can't even find where that Yosemite build is... It was in a GH issue... :cry:

**Comment by azazdeaz** [comment]
Thanks for the answer, here are my outputs:

```
$ elm-make --version
elm-make 0.2 (Elm Platform 0.15.1)

Usage: elm-make [FILES...] [--output FILE] [--yes] [--report FORMAT] [--warn]
                [--docs FILE]
  build Elm projects

Available options:
  -h,--help                Show this help text
  --output FILE            Write output to FILE.
  --yes                    Reply 'yes' to all automated prompts.
  --report FORMAT          Format of error and warning reports (e.g.
                           --report=json)
  --warn                   Report warnings to improve code quality.
  --docs FILE              Write documentation to FILE as JSON.

To learn more about a particular command run:
    elm-make COMMAND --help

```

```
$ node_modules/.bin/webpack
Hash: 86c4f52e75114dc197c0
Version: webpack 1.12.3
Time: 4606ms
     Asset       Size  Chunks             Chunk Names
index.html  246 bytes          [emitted]  
  index.js     461 kB       0  [emitted]  main
   [0] ./src/index.js 128 bytes {0} [built]
    + 2 hidden modules

WARNING in ./src/Main.elm
Critical dependencies:
12306:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./src/Main.elm 12306:113-120
```

But if you saying that some upcoming Elm release will resolve this warning i'm perfectly satisfied. So (since everything is working well) you can close this issue from me.

**Comment by justinwoo** [comment]
I would like some help getting rid of this webpack issue though... maybe this is a task for the super curious :grey_question: 

I think keeping this open is fine for now, especially since other users will see warning too with the current package available on the elm frontpage.

**Comment by azazdeaz** [comment]
Okay, tell me please if i can do anything to help!

**Comment by justinwoo** [comment]
Elm 0.16 came out today! :cool:

Try upgrading to that and elm-simple-loader 1.0.0. Should be good!

**Comment by azazdeaz** [comment]
Sorry, i having a hard time upgrading my elm packages. I'll report as soon as i can figure it out what am i doing wrong.

**Comment by azazdeaz** [comment]
Finally, i got working everithing on elm v0.16! But i still have that warning :(

```
$ elm-make --version
elm-make 0.16 (Elm Platform 0.16.0)
```

```
$ node_modules/.bin/webpack
Success! Compiled 1 modules.                                        
Successfully generated elm.js
Hash: ebb1eae5bf7137a9ceb6
Version: webpack 1.12.9
Time: 838ms
     Asset       Size  Chunks             Chunk Names
index.html  417 bytes          [emitted]  
  index.js     408 kB       0  [emitted]  main
   [0] ./src/index.js 128 bytes {0} [built]
    + 2 hidden modules

WARNING in ./src/Main.elm
Critical dependencies:
8969:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./src/Main.elm 8969:113-120
```

```
elm-simple-loader@1.0.1
```

And here is the repo online: https://github.com/azazdeaz/elm-lost-in-migration-game

**Comment by justinwoo** [comment]
Oh... right... I forgot that there were `require` calls all over `elm-html` and other packages. Well then...

I guess we do need to find a real solution sometime. Someone's got to know how to suppress Webpack warnings, right?

**Comment by justinwoo** [comment]
Okay... apparently it's all pushed on to the user :cry: 

You can add `module.noParse` to get rid of the warning. Better than nothing I guess. Issue here: https://github.com/webpack/webpack/issues/887

Using your project as an example, now I have this:

``` js
var webpack = require('webpack')
var path = require('path')

module.exports = {
  entry: './src/index.js',
  output: {
    path: './build',
    filename: 'index.js'
  },
  module: {
    loaders: [
      {
        test: /\.elm$/,
        loader: 'elm-simple-loader',
        include: path.join(__dirname, 'src'),
        exclude: /node_modules/
      }, {
        test: /\.(html)/,
        include: path.join(__dirname, 'src'),
        loader: 'file?name=[name].[ext]'
      }
    ],
    noParse: [/.elm$/]
  }
}
```

(I sent you a PR here: https://github.com/azazdeaz/elm-lost-in-migration-game/pull/1)

And this will get rid of the warning. Not ideal, since everyone has to set this crap up manually, but I guess I could justify it by saying "you have to add loader configs anyway hurr durr".

Hope this helps somewhat.

**Comment by azazdeaz** [comment]
Wow, thanks! It works great!

I don't think that  anyone would mind to set one more parameter in the webpack config.

Thanks again!

**Comment by justinwoo** [comment]
np, glad it works! :beers:
