### ISSUE TITLE
ReferenceError: Elm is not defined

### ISSUE THREAD

**Issue by draunkin** [justinwoo/elm-simple-loader#2]
Using the latest elm 0.17 I get an invalid reference in the output bundle.

>   }).call(this);
>     module.exports = Elm;
> /***/ }

The export appears after an IIFE (which I assume has been added in elm-make more recently?)

if I modify a line in index.js from this loader
was : 
`var output = '' + data + '\n' + 'module.exports = Elm;';`
now: 
`var output = '' + data + '\n';`

it works and I no longer get the reference error.

**Comment by justinwoo** [comment]
Cool, looks like Elm 0.17 builds a real module now. I pushed out a new version ([1.1.0](https://www.npmjs.com/package/elm-simple-loader)) which strips this export statement now.
